extends RefCounted
const Store=preload("res://core/save_store.gd")
const Click=preload("res://tests/interface_ui_cases.gd")

const Home=preload("res://tests/home_ui_cases.gd")

static func art_choices(t) -> void:
 var ui=t.ui;var settings=ui.display_settings
 var before=ui.game.export_snapshot();var choices=settings.art_choices.duplicate(true)
 var persist=settings.persistence_enabled;settings.persistence_enabled=false
 settings.art_choices.clear()
 await Click.press(t,"EncyclopediaCategory_enemies")
 var book=ui.find_child("Encyclopedia",true,false)
 book.show_entry(book.rows.filter(func(row):return row.category=="enemies" and row.id=="six_bind")[0]);await t.frames()
 var picker=ui.find_child("EncyclopediaArtStyle",true,false)
 var picture=ui.find_child("EncyclopediaEnemyImage",true,false)
 t.check(picker.selected==1 and picture.enemy_sprite.texture.resource_path.ends_with("enemy-six-bind-formal-v1.png"),"ART six binds defaults to supplied formal art in encyclopedia")
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 t.check(not is_instance_valid(picture.enemy_sprite) and book.selected=="six_bind","ART individual selector restores procedural test artwork and retains book focus")
 picker.select(1);picker.item_selected.emit(1);await t.frames()
 t.check(is_instance_valid(picture.enemy_sprite),"ART switching back recreates formal preview immediately")
 await Click.press(t,"EncyclopediaCategory_cards")
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and not settings.has_formal_art("cards",row.id))[0]);await t.frames()
 picker=ui.find_child("EncyclopediaArtStyle",true,false)
 var face=ui.find_child("DisplayCard_encyclopedia_"+book.selected,true,false)
 t.check(picker.is_item_disabled(1) and ui.find_child("EncyclopediaArtNote",true,false).text=="正式版立绘未添加" and face.get_node("CardIllustration").texture==face.ILLUSTRATIONS[face.symbol],"ART missing formal card keeps original illustration with explicit unavailable option")
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 t.check(settings.art_style("enemies","six_bind")=="formal" and ui.game.export_snapshot()==before,"ART card preference neither changes enemy preference nor gameplay state")
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id=="crossed_legs")[0]);await t.frames()
 picker=ui.find_child("EncyclopediaArtStyle",true,false)
 face=ui.find_child("DisplayCard_encyclopedia_crossed_legs",true,false)
 var art=face.get_node("CardIllustration");var official=art.texture
 t.check(picker.selected==1 and not picker.is_item_disabled(1) and official.resource_path.ends_with("card-crossed-legs-formal-v1.png") and official.get_image().detect_alpha()!=Image.ALPHA_NONE,"ART crossed legs defaults to supplied transparent formal portrait over unchanged card backdrop")
 face.flip_requested.emit();await t.frames()
 t.check(art.texture==official and art.stretch_mode==TextureRect.STRETCH_KEEP_ASPECT_CENTERED and art.material==null,"ART both card faces keep the same full portrait without stretching or color key")
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 t.check(art.texture==face.ILLUSTRATIONS.crossed_legs,"ART crossed legs test drawing remains selectable")
 picker.select(1);picker.item_selected.emit(1);await t.frames()
 t.check(art.texture==official and ui.game.export_snapshot()==before,"ART switching formal portrait changes no card rules or game state")
 await t.capture("ui-crossed-legs-formal.png")
 await infusion_art_faces(t,book)
 await binding_art_variants(t,book)
 await hannya_art_group(t,book)
 settings.art_choices=choices;settings.persistence_enabled=persist

static func inspect_card_art(t) -> void:
 var ui=t.ui;var book=ui.find_child("Encyclopedia",true,false)
 var Pointer=preload("res://tests/target_sidebar_ui_cases.gd")
 var Keys=preload("res://tests/keyboard_ui_cases.gd")
 var Touch=preload("res://tests/touch_ui_cases.gd")
 var settings=ui.display_settings;var choices=settings.art_choices.duplicate(true)
 var persist=settings.persistence_enabled;settings.persistence_enabled=false
 settings.set_art_style("cards","infusion","formal")
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id=="infusion")[0]);await t.frames()
 var face=ui.find_child("DisplayCard_encyclopedia_infusion",true,false)
 var before=ui.game.export_snapshot();var scroll=book.detail.get_parent().scroll_vertical
 for free in [false,true]:
  if face.free_face!=free: face.flip_requested.emit();await t.frames()
  var source=face.get_node("CardIllustration").texture
  await Pointer.press(t,face);await t.frames()
  var modal=ui.modal_region();var image=ui.find_child("ArtInspectionImage",true,false)
  t.check(modal!=null and image.texture==source and image.texture.get_size()==source.get_size(),"ART INSPECT native card click uses current face source texture without thumbnail resampling")
  var area=ui.find_child("ArtInspectionScroll",true,false).get_global_rect()
  var rect=image.get_global_rect()
  t.check(area.encloses(rect) and rect.get_center().distance_to(modal.get_global_rect().get_center())<1 and is_equal_approx(rect.size.x/rect.size.y,source.get_size().x/source.get_size().y),"ART INSPECT full artwork fits centrally without cropping or distortion")
  await Keys.tap(t,KEY_F);await Keys.tap(t,KEY_Z)
  t.check(ui.game.export_snapshot()==before and ui.show_encyclopedia,"ART INSPECT keys cannot trigger background game actions")
  await Pointer.press(t,ui.find_child("ArtInspectionZoom",true,false));await t.frames()
  t.check((image.size*image.get_screen_transform().get_scale().abs()).is_equal_approx(source.get_size()),"ART INSPECT one-to-one mode maps source pixels to screen pixels")
  if free:
   var window_size=t.root.size
   t.root.size=Vector2i(1280,720);await t.frames(8)
   t.check((image.size*image.get_screen_transform().get_scale().abs()).is_equal_approx(source.get_size()),"ART INSPECT native pixel size survives non-baseline window stretch")
   t.root.size=window_size;await t.frames(8)
  await Pointer.press(t,ui.find_child("ArtInspectionZoom",true,false));await t.frames()
  if free: await t.capture("ui-card-art-inspection.png")
  await Keys.tap(t,KEY_ESCAPE)
  t.check(ui.modal_region()==null and ui.show_encyclopedia and book.selected=="infusion" and book.detail.get_parent().scroll_vertical==scroll,"ART INSPECT Escape dismisses only art and preserves book position")
 settings.set_art_style("cards","infusion","test");await t.frames()
 await Touch.tap(t,face);await t.frames()
 t.check(ui.find_child("ArtInspectionImage",true,false).texture==face.ILLUSTRATIONS.infusion,"ART INSPECT touch opens selected test artwork")
 t.check(ui.find_child("ArtInspectionClose",true,false)==null,"ART INSPECT no dedicated close button")
 await Touch.tap(t,ui.find_child("ArtInspectionZoom",true,false));await t.frames()
 var native_blank=ui.find_child("ArtInspectionScroll",true,false).get_global_rect().position+Vector2(12,12)
 await Touch.finger(t,native_blank,true);await Touch.finger(t,native_blank,false);await t.frames()
 t.check(ui.modal_region()==null and ui.show_encyclopedia,"ART INSPECT native-mode inner dark area dismisses art")
 await Touch.tap(t,face);await t.frames()
 var blank=ui.find_child("ArtInspectionScroll",true,false).get_global_rect().position+Vector2(12,12)
 await Touch.finger(t,blank,true);await Touch.finger(t,blank,false);await t.frames()
 t.check(ui.modal_region()==null and ui.show_encyclopedia,"ART INSPECT touch on inner dark area closes only art")
 await Pointer.press(t,face);await t.frames()
 await t.move_mouse(Vector2(10,450));await t.mouse_button(Vector2(10,450),MOUSE_BUTTON_LEFT,true);await t.mouse_button(Vector2(10,450),MOUSE_BUTTON_LEFT,false);await t.frames()
 t.check(ui.modal_region()==null and ui.show_encyclopedia and ui.game.export_snapshot()==before,"ART INSPECT backdrop consumes dismissal without click-through")
 await Pointer.press(t,face);await t.frames()
 ui._notification(Node.NOTIFICATION_WM_GO_BACK_REQUEST);await t.frames()
 t.check(ui.modal_region()==null and ui.show_encyclopedia,"ART INSPECT Android back dismisses only the inspection")
 book._inspect_card(face)
 var old=ui.modal_region();old.dismiss();book._inspect_card(face)
 t.check(ui.modal_region()!=null and ui.modal_region()!=old,"ART INSPECT same-frame reopen keeps modal identity")
 ui.modal_region().dismiss();await t.frames()
 book._inspect_card(face)
 ui._close_drawers();ui._refresh_drawers();await t.frames()
 t.check(ui.modal_region()==null,"ART INSPECT owner exit releases active modal")
 ui._open_drawer("show_encyclopedia");await t.frames()
 await Click.press(t,"EncyclopediaCategory_cards")
 settings.art_choices=choices;settings.persistence_enabled=persist;settings.apply()

static func hannya_art_group(t,book) -> void:
 var ui=t.ui;var settings=ui.display_settings;var before=ui.game.export_snapshot()
 var members=["hannya_1","hannya_2","hannya_3","hannya_4","good_soup","hannya_swallow","hannya_infusion","hannya_henshin"]
 var holder=VBoxContainer.new();holder.position=Vector2(-4000,-4000);ui.add_child(holder)
 var faces=[]
 for id in members:
  ui._display_card(id,holder,Callable(),"hannya_group_"+id,Vector2(200,320),"",false)
  faces.append(holder.find_child("DisplayCard_hannya_group_"+id,true,false))
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id=="hannya_1")[0]);await t.frames()
 var picker=ui.find_child("EncyclopediaArtStyle",true,false)
 for style in ["test","formal"]:
  var index=0 if style=="test" else 1
  picker.select(index);picker.item_selected.emit(index);await t.frames()
  for face in faces:
   var expected=face.ILLUSTRATIONS[face.symbol] if style=="test" else settings.art_texture("cards",face.symbol,face.effect_free)
   t.check(settings.art_style("cards",face.symbol)==style and face.get_node("CardIllustration").texture==expected,"HANNYA ART main selector updates every live derivative: "+face.symbol+" "+style)
 settings.set_art_style("cards","hannya_infusion","test");await t.frames()
 t.check(members.all(func(id):return settings.art_style("cards",id)=="test") and faces.all(func(face):return face.get_node("CardIllustration").texture==face.ILLUSTRATIONS[face.symbol]),"HANNYA ART derivative changes the shared choice and refreshes all existing faces")
 t.check(["infusion","henshin","light_as_swallow"].all(func(id):return settings.art_style("cards",id)=="formal") and ui.game.export_snapshot()==before,"HANNYA ART normal originals and gameplay remain independent")
 var path="res://build/hannya-art-preference-%s.cfg" % Time.get_ticks_usec()
 var config=ConfigFile.new();config.set_value("art","choices",{"cards":{"hannya_2":"formal","hannya_1":"test","hannya_henshin":"formal"}});config.save(path)
 var restored=preload("res://ui/display_settings.gd").new();restored.path=path;restored.initialize(t.root)
 t.check(members.all(func(id):return restored.art_style("cards",id)=="test") and restored.art_choices.cards.keys()==["hannya_1"],"HANNYA ART main preference wins conflicting legacy entries without separate derivative keys")
 restored.set_art_style("cards","good_soup","formal");restored.initialize(t.root)
 t.check(members.all(func(id):return restored.art_style("cards",id)=="formal"),"HANNYA ART derivative selection survives preference reload for the entire family")
 config.set_value("art","choices",{"cards":{"hannya_3":"test"}});config.save(path);restored.initialize(t.root)
 t.check(restored.art_style("cards","hannya_1")=="test","HANNYA ART legacy derivative-only preference is retained")
 DirAccess.remove_absolute(path)
 settings.apply();settings.set_art_style("cards","hannya_1","formal")
 holder.queue_free();await t.frames()

static func binding_art_variants(t,book) -> void:
 var ui=t.ui;var settings=ui.display_settings;var before=ui.game.export_snapshot()
 var previous=[settings.fixed_hero_portrait,settings.chastity_locks_enabled,settings.cursed_plate_start,settings.cursed_plate_masochist_mode]
 settings.set_fixed_hero_portrait(false)
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id=="binding_enthusiast")[0]);await t.frames()
 var picker=ui.find_child("EncyclopediaArtStyle",true,false)
 var face=ui.find_child("DisplayCard_encyclopedia_binding_enthusiast",true,false)
 var art=face.get_node("CardIllustration")
 var original="res://assets/art/card-binding-enthusiast-formal-v1.png"
 var fixed="res://assets/art/card-binding-enthusiast-fixed-formal-v1.png"
 t.check(picker.item_count==4 and picker.selected==1 and art.texture.resource_path==original,"BINDING ART default follows mode with both formal variants available")
 settings.set_fixed_hero_portrait(true);await t.frames()
 t.check(art.texture.resource_path==fixed,"BINDING ART changing fixed portrait mode refreshes existing card")
 face.flip_requested.emit();await t.frames()
 t.check(art.texture.resource_path==fixed,"BINDING ART alternate applies to both card faces")
 picker.select(2);picker.item_selected.emit(2);await t.frames()
 t.check(settings.art_style("cards","binding_enthusiast")=="original" and art.texture.resource_path==original,"BINDING ART explicit original overrides enabled mode")
 picker.select(3);picker.item_selected.emit(3);await t.frames()
 settings.set_fixed_hero_portrait(false);await t.frames()
 t.check(art.texture.resource_path==fixed,"BINDING ART explicit alternate remains selectable with mode off")
 var path=settings.path;var persist=settings.persistence_enabled
 settings.path="res://build/binding-art-preference-%s.cfg" % Time.get_ticks_usec();settings.persistence_enabled=true;settings.save()
 var restored=preload("res://ui/display_settings.gd").new();restored.path=settings.path;restored.initialize(t.root)
 t.check(restored.art_style("cards","binding_enthusiast")=="fixed" and restored.art_texture("cards","binding_enthusiast").resource_path==fixed,"BINDING ART explicit variant survives preference reload")
 restored.set_art_style("cards","binding_enthusiast","original");restored.initialize(t.root)
 t.check(restored.art_style("cards","binding_enthusiast")=="original" and restored.art_texture("cards","binding_enthusiast").resource_path==original,"BINDING ART original variant survives preference reload")
 restored.set_art_style("cards","binding_enthusiast","formal");restored.set_fixed_hero_portrait(true);restored.initialize(t.root)
 t.check(restored.art_style("cards","binding_enthusiast")=="formal" and restored.art_texture("cards","binding_enthusiast").resource_path==fixed,"BINDING ART automatic choice restores saved mode")
 settings.path=path;settings.persistence_enabled=persist;settings.apply()
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 settings.set_fixed_hero_portrait(true);await t.frames()
 t.check(art.texture==face.ILLUSTRATIONS.binding_enthusiast,"BINDING ART mode does not override explicit test style")
 picker.select(1);picker.item_selected.emit(1);await t.frames()
 settings.set_fixed_hero_portrait(false);await t.frames()
 t.check(art.texture.resource_path==original and ui.game.export_snapshot()==before,"BINDING ART returning to automatic restores mode tracking without gameplay changes")
 settings.fixed_hero_portrait=previous[0];settings.chastity_locks_enabled=previous[1];settings.cursed_plate_start=previous[2];settings.cursed_plate_masochist_mode=previous[3]

static func infusion_art_faces(t,book) -> void:
 var ui=t.ui;var settings=ui.display_settings;var before=ui.game.export_snapshot()
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id=="infusion")[0]);await t.frames()
 for id in ["infusion","hannya_infusion"]:
  var face=ui.find_child("DisplayCard_encyclopedia_"+id,true,false)
  var art=face.get_node("CardIllustration")
  t.check(not face.effect_free and art.texture.resource_path.ends_with("card-infusion-leg-formal-v1.png"),"INFUSION ART bound face starts with empowered leg: "+id)
  face.flip_requested.emit();await t.frames()
  t.check(face.effect_free and art.texture.resource_path.ends_with("card-infusion-hand-formal-v1.png"),"INFUSION ART real face flip switches to empowered hand: "+id)
  settings.set_art_style("cards",id,"test");await t.frames()
  t.check(art.texture==face.ILLUSTRATIONS[id],"INFUSION ART test style restores original SVG: "+id)
  face.flip_requested.emit();await t.frames()
  t.check(not face.effect_free and art.texture==face.ILLUSTRATIONS[id],"INFUSION ART flipping in test style retains original SVG: "+id)
  settings.set_art_style("cards",id,"formal");await t.frames()
  t.check(art.texture.resource_path.ends_with("card-infusion-leg-formal-v1.png") and art.stretch_mode==TextureRect.STRETCH_KEEP_ASPECT_CENTERED,"INFUSION ART formal restore follows current face without stretching: "+id)
 t.check(ui.game.export_snapshot()==before,"INFUSION ART flips and style changes preserve game snapshot")

static func run(t) -> void:
 var store=Store.new("res://build/home-ui-"+str(Time.get_ticks_usec()))
 await Home.boot(t,store)
 var ui=t.ui
 var initial=ui.game.export_snapshot()
 await Click.press(t,"HomeEncyclopedia")
 t.check(ui.show_home and ui.show_encyclopedia and ui.find_child("Encyclopedia",true,false)!=null,"BOOK opens above home")
 var equipment_picture=ui.find_child("EncyclopediaEquipmentImage",true,false)
 var first_entry=ui.find_child("EncyclopediaEntries",true,false).get_child(0)
 t.check(equipment_picture!=null and first_entry.icon==equipment_picture.texture and equipment_picture.stretch_mode==TextureRect.STRETCH_KEEP_ASPECT_CENTERED and equipment_picture.get_parent().get_global_rect().encloses(equipment_picture.get_global_rect()),"BOOK list thumbnail and bounded detail image share the equipment art")
 await t.capture("ui-equipment-book-images.png")
 var equipment_search=ui.find_child("EncyclopediaSearch",true,false)
 equipment_search.text="左手胶带包裹";equipment_search.text_changed.emit(equipment_search.text);await t.frames()
 await Click.press(t,"EncyclopediaEntry_composite_wrap_left_straight3")
 var wrap_description=ui.find_child("EncyclopediaDescription",true,false)
 t.check(wrap_description.text.contains("\n\n包裹：耐久24；") and wrap_description.get_theme_constant("line_spacing")==6 and wrap_description.get_theme_font_size("font_size")==18,"BOOK restraint description uses compact sections and readable line spacing")
 equipment_search.text="";equipment_search.text_changed.emit("");await t.frames()
 var gag_search=ui.find_child("EncyclopediaSearch",true,false)
 gag_search.text="普通假阳具口球";gag_search.text_changed.emit(gag_search.text);await t.frames()
 await Click.press(t,"EncyclopediaEntry_equipment_mouth_band_2_1")
 var gag_text=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 t.check(gag_text.contains("品质倍率×0.25") and gag_text.contains("×0.375／0.25／0.125") and not gag_text.contains("组合效果以该品质"),"BOOK gag detail shows grade and all tightness multipliers")
 t.check(not gag_text.contains("紧度：剩余耐久"),"BOOK gag retains useful casting numbers without generic tightness explanation")
 t.check(ui.game.export_snapshot()==initial,"BOOK equipment rules remain read-only")
 gag_search.text="";gag_search.text_changed.emit("");await t.frames()
 await Click.press(t,"EncyclopediaCategory_items")
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==ui.game.Tools.TYPES.size() and not ui.find_child("EncyclopediaGrade",true,false).visible,"BOOK item category lists all definitions without irrelevant grade controls")
 var item_group=ui.find_child("EncyclopediaGroup",true,false)
 var item_branches=range(1,item_group.item_count).map(func(index):return item_group.get_item_metadata(index))
 t.check(item_branches==["药剂","卷轴","工具"],"BOOK separate potion, scroll and tool filters")
 item_group.select(2);item_group.item_selected.emit(2);await t.frames()
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==ui.game.Tools.TYPES.values().filter(func(spec):return spec.get("category","")=="scroll").size(),"BOOK scroll filter matches actual registry")
 item_group.select(0);item_group.item_selected.emit(0);await t.frames()
 var item_search=ui.find_child("EncyclopediaSearch",true,false)
 item_search.text="锯条";item_search.text_changed.emit(item_search.text);await t.frames()
 await Click.press(t,"EncyclopediaEntry_saw")
 var item_detail=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==1 and item_detail.contains("7点真实伤害") and item_detail.contains("使用次数：2") and item_detail.contains("安装后") and ui.find_child("EncyclopediaItemIcon",true,false).symbol=="saw","BOOK searchable tool detail shows damage, uses and shared installation effect")
 t.check(ui.game.export_snapshot()==initial and not store.has_files("tower"),"BOOK item browsing neither starts a run nor changes gameplay")
 await t.capture("ui-encyclopedia-items.png")
 item_search.text="";item_search.text_changed.emit("");await t.frames()
 await Click.press(t,"EncyclopediaCategory_special")
 var image_search=ui.find_child("EncyclopediaSearch",true,false)
 image_search.text=ui.game.SpecialEquipment.TYPES.urethral_rod_medium.name;image_search.text_changed.emit(image_search.text);await t.frames()
 await Click.press(t,"EncyclopediaEntry_urethral_rod_medium")
 equipment_picture=ui.find_child("EncyclopediaEquipmentImage",true,false)
 t.check(equipment_picture!=null and equipment_picture.texture.resource_path.ends_with("focus-c-silicone-urethral-rod.png"),"BOOK selecting illustrated special equipment shows the existing local picture")
 image_search.text="";image_search.text_changed.emit("");await t.frames()
 await Click.press(t,"EncyclopediaEntry_nipple_clamp_low")
 t.check(ui.find_child("EncyclopediaEquipmentImage",true,false)==null and ui.game.export_snapshot()==initial,"BOOK missing-image selection clears previous picture without changing gameplay")
 for category in ["equipment","special","enemies","cards"]:
  await Click.press(t,"EncyclopediaCategory_"+category)
  t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()>0,"BOOK populated category "+category)
 await art_choices(t)
 await inspect_card_art(t)
 var hidden_variants=["magic_hand_gift","hannya_swallow","hannya_infusion","hannya_henshin","hannya_2","hannya_3","hannya_4","good_soup"]
 t.check(hidden_variants.all(func(id):return ui.find_child("EncyclopediaEntry_"+id,true,false)==null),"BOOK UI omits duplicate special card variants")
 var variant_search=ui.find_child("EncyclopediaSearch",true,false)
 for title in ["身轻如燕","灌注","魔术手","henshin"]:
  variant_search.text=title;variant_search.text_changed.emit(title);await t.frames()
  var matches=ui.find_child("EncyclopediaEntries",true,false).get_children()
  t.check(matches.filter(func(button):return button.text.begins_with(title+" ·")).size()==1 and hidden_variants.all(func(id):return ui.find_child("EncyclopediaEntry_"+id,true,false)==null),"BOOK UI search has one original-name row without variant duplicates: "+title)
 variant_search.text="品相完美";variant_search.text_changed.emit(variant_search.text);await t.frames()
 t.check(ui.find_child("EncyclopediaEntry_henshin",true,false)!=null and hidden_variants.all(func(id):return ui.find_child("EncyclopediaEntry_"+id,true,false)==null),"BOOK UI special name search finds its original without a duplicate row")
 variant_search.text="";variant_search.text_changed.emit("");await t.frames()
 var family_book=ui.find_child("Encyclopedia",true,false)
 for term in ["般若汤","般若汤-其二","般若汤-其三","般若汤-其四","好汤喝够"]:
  variant_search.text=term;variant_search.text_changed.emit(term);await t.frames()
  var soup_rows=ui.find_child("EncyclopediaEntries",true,false).get_children()
  t.check(soup_rows.size()==1 and soup_rows[0].name=="EncyclopediaEntry_hannya_1" and ui.find_child("DisplayCard_encyclopedia_good_soup",true,false)!=null,"BOOK soup and descendant searches lead only to complete first-stage family: "+term)
 variant_search.text="";variant_search.text_changed.emit("");await t.frames()
 for original in family_book.Catalog.CARD_VARIANTS:
  family_book.show_entry(family_book.rows.filter(func(row):return row.category=="cards" and row.id==original)[0]);await t.frames()
  var original_face=ui.find_child("DisplayCard_encyclopedia_"+original,true,false)
  var child_id=family_book.Catalog.CARD_VARIANTS[original][0]
  var child_face=ui.find_child("DisplayCard_encyclopedia_"+child_id,true,false)
  t.check(original_face!=null and child_face!=null and child_face.drag_payload.is_empty(),"BOOK original and special variant share the detail page: "+original)
  var old_side=original_face.free_face;var child_side=child_face.free_face
  child_face.flip_requested.emit();await t.frames()
  t.check(child_face.free_face!=child_side and original_face.free_face==old_side and ui.game.export_snapshot()==initial,"BOOK variant flips independently without changing original or game: "+original)
 family_book.show_entry(family_book.rows.filter(func(row):return row.category=="cards" and row.id=="hannya_1")[0]);await t.frames()
 var flow=ui.find_child("EncyclopediaCardFamily",true,false)
 for stage in range(1,4):
  var soup_face=ui.find_child("DisplayCard_encyclopedia_hannya_%d" % stage,true,false)
  var next_name=family_book.Catalog.B.CARD_NAMES["hannya_%d" % (stage+1)]
  t.check(t.visible_text(soup_face).contains(next_name+"加入弃牌堆"),"BOOK visible soup card spells out generated card name: "+next_name)
 t.check(flow.get_child_count()==8 and family_book.Catalog.related_cards("hannya_1").all(func(id):return ui.find_child("DisplayCard_encyclopedia_"+id,true,false)!=null),"BOOK soup page includes every downstream card in one scrollable family")
 t.check(flow.get_children().all(func(section):return section.position.x>=0 and section.position.x+section.size.x<=flow.size.x+1),"BOOK card family wraps inside available detail width")
 var family_scroll=ui.find_child("EncyclopediaDetail",true,false).get_parent()
 family_scroll.scroll_vertical=10000;await t.frames()
 t.check(ui.find_child("DisplayCard_encyclopedia_good_soup",true,false).get_global_rect().intersects(family_scroll.get_global_rect()),"BOOK final descendant remains reachable by scrolling")
 var branch=ui.find_child("EncyclopediaGroup",true,false)
 var branches=range(1,branch.item_count).map(func(index):return branch.get_item_metadata(index))
 t.check(ui.game.Cards.Rules.TYPES.values().all(func(label):return label+"牌" in branches) and branches.all(func(label):return branches.count(label)==1),"BOOK includes registered card branches and distinct combined-type branches")
 branch.select(4);branch.item_selected.emit(4);await t.frames()
 t.check(t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains("慌乱"),"BOOK dedicated curse branch")
 var face=ui.find_child("DisplayCard_encyclopedia_panic",true,false)
 t.check(face!=null and face.drag_payload.is_empty() and not face.lift_on_hover and face.size*face.scale==Vector2(300,480),"BOOK uses enlarged portrait card face with equally enlarged text and no gameplay drag")
 face.flip_requested.emit();await t.frames()
 t.check(not face.free_face and ui.game.export_snapshot()==initial and not store.has_files("tower"),"BOOK single-face curse cannot flip or start a run")
 var search=ui.find_child("EncyclopediaSearch",true,false)
 search.text="无匹配图鉴";search.text_changed.emit(search.text);await t.frames()
 t.check(t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains("暂无条目"),"BOOK search empty result")
 search.text="";search.text_changed.emit("");await t.frames()
 await t.capture("ui-encyclopedia-curse.png")
 branch.select(5);branch.item_selected.emit(5);await t.frames()
 var status_face=ui.find_child("DisplayCard_encyclopedia_tease",true,false)
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==ui.game.Cards.Rules.SPECS.values().filter(func(spec):return spec.card_type=="status").size() and status_face!=null and status_face.rarity=="status" and t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains("状态"),"BOOK status branch renders all registered status cards using the shared card face")
 branch.select(3);branch.item_selected.emit(3)
 var rarity=ui.find_child("EncyclopediaGrade",true,false)
 rarity.select(4);rarity.item_selected.emit(4);await t.frames()
 var ability_rows=ui.find_child("EncyclopediaEntries",true,false).get_children()
 var ability_detail=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 t.check(not ability_rows.is_empty() and ability_detail.contains("能力牌") and ability_detail.contains("稀有") and rarity.visible,"BOOK combines ability branch and rare filter without assuming first card ordering")
 await Click.press(t,"EncyclopediaCategory_relics");await t.frames()
 var doubao_book=ui.find_child("Encyclopedia",true,false)
 doubao_book.show_entry(doubao_book.rows.filter(func(row):return row.category=="relics" and row.id=="doubao")[0]);await t.frames()
 var whale=ui.find_child("EncyclopediaRelicIcon_deepseek",true,false)
 var whale_text=ui.find_child("EncyclopediaRelicDescription_deepseek",true,false)
 t.check(whale!=null and whale.glyph.texture==preload("res://ui/relic_icon.gd").ART.deepseek and whale.glyph.texture_filter==CanvasItem.TEXTURE_FILTER_NEAREST and whale_text.text.contains("能量变为0"),"BOOK Doubao entry includes independent pixel portrait and current DeepSeek effect")
 await t.capture("ui-deepseek-pixel-encyclopedia.png")
 t.check(not ui.find_child("EncyclopediaDescription",true,false).text.contains("能量变为0"),"BOOK alternate effect stays separate from Doubao description")
 var axe_book=ui.find_child("Encyclopedia",true,false)
 axe_book.show_entry(axe_book.rows.filter(func(row):return row.category=="relics" and row.id=="cursed_plate_lock")[0]);await t.frames()
 var cursed_text=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 var cursed_icon=ui.find_child("EncyclopediaRelicIcon",true,false)
 t.check(cursed_text.contains("前6回合") and cursed_text.contains("自动解锁并取下整件") and cursed_icon!=null and cursed_icon.glyph.texture==cursed_icon.ART.cursed_plate_lock,"CURSED PLATE encyclopedia shows dedicated artwork and automatic key removal rule")
 axe_book.show_entry(axe_book.rows.filter(func(row):return row.category=="relics" and row.id=="axe_amulet")[0]);await t.frames()
 var axe_text=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 var axe_icon=ui.find_child("EncyclopediaRelicIcon",true,false)
 t.check(axe_text.contains("斧护符") and axe_text.contains("罕见") and axe_text.contains("进入精英房、Boss房或监狱时，恢复20魔力") and axe_icon!=null and axe_icon.ART.has("axe_amulet"),"AXE encyclopedia shows uncommon name, entry effect and registered icon")
 rarity=ui.find_child("EncyclopediaGrade",true,false)
 t.check(range(1,rarity.item_count).map(func(i):return rarity.get_item_metadata(i))==ui.game.Relics.RARITIES.keys() and rarity.visible,"RELIC encyclopedia exposes registered rarity filters including special collectibles")
 rarity.select(3);rarity.item_selected.emit(3);await t.frames()
 var relic_rows=ui.find_child("EncyclopediaEntries",true,false).get_children()
 t.check(relic_rows.all(func(row):return row.icon!=null),"RELIC encyclopedia list reuses actual relic artwork")
 var relic_icon=ui.find_child("EncyclopediaRelicIcon",true,false)
 t.check(relic_icon!=null and relic_icon.glyph is TextureRect and relic_icon.glyph.texture==preload("res://ui/relic_icon.gd").ART[relic_icon.relic.id] and relic_icon.badge==null,"RELIC encyclopedia detail shows shared artwork without inventing a live counter")
 await t.capture("ui-encyclopedia-relics.png")
 t.check(relic_rows.size()==ui.game.Relics.TYPES.values().filter(func(r):return r.rarity=="rare").size() and ui.game.Relics.TYPES.values().any(func(r):return r.rarity=="rare" and t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains(r.name)),"RELIC rare filter selects actual registered rare relics")
 t.check(ui.game.export_snapshot()==initial and not store.has_files("tower"),"RELIC browsing and filtering never change the run or create a save")
 await t.close_information()
 t.check(ui.show_home and not ui.show_encyclopedia,"BOOK closes back to homepage")
 ui.persistence_enabled=false;ui.feedback_duration=0.04
 await card_terms(t)
 await static_cards(t)
 await character_catalog(t)

# Encyclopedia faces have no physical instance: both sides must show the metadata terms of the
# currently drawn face, one box each, without covering the card or intercepting its own click
# (docs/spec/card-terms.md「接口」「失败语义」).
static func card_terms(t) -> void:
 var ui=t.ui
 var Interface=preload("res://tests/interface_ui_cases.gd")
 var Keys=preload("res://tests/keyboard_ui_cases.gd")
 var Pointer=preload("res://tests/target_sidebar_ui_cases.gd")
 ui.restart(42);await t.frames()
 ui._open_drawer("show_encyclopedia");await t.frames()
 await Click.press(t,"EncyclopediaCategory_cards")
 var book=ui.find_child("Encyclopedia",true,false)
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id=="mana_search")[0]);await t.frames()
 var face=ui.find_child("DisplayCard_encyclopedia_mana_search",true,false)
 t.check(face!=null and not face.single_face,"TERMS UI encyclopedia sample card has two faces")
 if face==null: return
 var bound=Interface.pinned_terms("mana_search","bound");var free=Interface.pinned_terms("mana_search","free")
 t.check(bound.size()==1 and free.size()==2 and bound!=free,"TERMS UI encyclopedia sample faces carry different term sets")
 var before=ui.game.export_snapshot();var version=ui.view.version
 await t.move_mouse(Vector2(70,300));await t.frames()
 var anchor=face.get_global_rect()
 await t.move_mouse(anchor.get_center());await t.frames()
 var popup=ui.find_child("TermExplanation",true,false)
 t.check(popup!=null and Interface.term_boxes(popup)==bound,"TERMS UI encyclopedia hover renders one box per bound term in metadata order: "+str(Interface.term_boxes(popup)))
 var boxes=popup.get_child(0).get_children().filter(func(node):return node is PanelContainer) if popup!=null else []
 t.check(popup!=null and boxes.size()==bound.size(),"TERMS UI encyclopedia box count equals the bound face term count")
 var rect=popup.get_global_rect() if popup!=null else Rect2()
 t.check(popup!=null and not rect.intersects(anchor) and Rect2(0,0,1600,900).encloses(rect),"TERMS UI term boxes clear the anchor card and stay inside the viewport")
 await Pointer.press(t,face);await t.frames()
 t.check(ui.modal_region()!=null,"TERMS UI real click on the hovered card still opens its own surface")
 await Keys.tap(t,KEY_ESCAPE);await t.frames()
 t.check(ui.modal_region()==null and ui.show_encyclopedia,"TERMS UI escape closes only the card surface")
 await t.move_mouse(Vector2(70,300));await t.frames()
 face.flip_requested.emit();await t.frames()
 await t.move_mouse(face.get_global_rect().get_center());await t.frames()
 popup=ui.find_child("TermExplanation",true,false)
 t.check(popup!=null and Interface.term_boxes(popup)==free and Interface.term_boxes(popup)!=bound,"TERMS UI flipping the face replaces the boxes with the other side terms: "+str(Interface.term_boxes(popup)))
 t.check(ui.game.export_snapshot()==before and ui.view.version==version,"TERMS UI hover, flip and close change no state and no view version")
 ui._show_term(face,{"label":"","detail":"短提示"})
 await t.frames()
 var plain=ui.find_child("TermExplanation",true,false)
 t.check(plain!=null and Interface.term_boxes(plain).is_empty() and t.visible_text(plain).strip_edges()=="短提示","TERMS UI a call without terms keeps the plain single panel")
 ui._hide_term()
 await t.close_information()

static func character_catalog(t) -> void:
 var ui=t.ui;var before=ui.game.export_snapshot()
 ui._open_drawer("show_encyclopedia");await t.frames()
 var picker=ui.find_child("EncyclopediaCharacter",true,false)
 t.check(picker!=null and picker.item_count==2 and picker.selected==0,"BOOK includes character choice inside encyclopedia")
 picker.select(1);picker.item_selected.emit(1);await t.frames()
 await Click.press(t,"EncyclopediaCategory_cards")
 var book=ui.find_child("Encyclopedia",true,false)
 t.check(book.rows.any(func(row):return row.category=="cards" and row.id=="witch_authority") and not book.rows.any(func(row):return row.category=="cards" and row.id=="fire_mastery"),"BOOK witch collection includes exclusive cards and excludes incompatible originals")
 book.show_entry(book.rows.filter(func(row):return row.id=="witch_escape_practice")[0]);await t.frames()
 var training=ui.find_child("DisplayCard_encyclopedia_witch_escape_practice",true,false)
 t.check(t.visible_text(training).contains("初始") and t.visible_text(training).contains("1×3") and ui.find_child("EncyclopediaCardFamily",true,false).get_child_count()==6,"BOOK starter training and all five evolutions share one page with separate-hit notation")
 book.show_entry(book.rows.filter(func(row):return row.id=="witch_authority")[0]);await t.frames()
 var authority=ui.find_child("DisplayCard_encyclopedia_witch_authority",true,false)
 for side in range(2):
  var warning=authority.get_node("CardText/Content/CardWarning")
  t.check(warning.text=="锁定回合结束按钮！" and warning.get_theme_color("font_color")==ui.RED,"BOOK authority warning is red on both faces")
  authority.flip_requested.emit();await t.frames()
 book.show_entry(book.rows.filter(func(row):return row.id=="witch_mana_transfer")[0]);await t.frames()
 var transfer=ui.find_child("DisplayCard_encyclopedia_witch_mana_transfer",true,false)
 for side in range(2):
  t.check(transfer.get_node("CardText/Content/CardClassification").text.begins_with("魔法" if transfer.free_face else "技能"),"BOOK mixed-type card class follows selected face")
  transfer.flip_requested.emit();await t.frames()
 await Click.press(t,"EncyclopediaCategory_relics")
 t.check(book.rows.any(func(row):return row.id=="witch_amulet") and not book.rows.any(func(row):return row.id=="shining_lamp"),"BOOK witch relic collection uses its own pool")
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 t.check(book.rows.any(func(row):return row.id=="shining_lamp") and not book.rows.any(func(row):return row.id=="witch_amulet") and ui.game.export_snapshot()==before,"BOOK switching original relic collection leaves active character and run unchanged")
 await t.close_information()

static func static_cards(t) -> void:
 var ui=t.ui
 ui.game_factory=preload("res://tests/game_fixture.gd")
 ui.restart(42);await t.frames()
 ui.show_home=false
 ui.game._discard_end()
 var held=preload("res://tests/curse_cases.gd").give(ui.game,"confluence")
 for slot in ["eyes","ankle","thigh"]: ui.game.add_fixture(slot,8)
 ui.game._install_template("mouth_band","mouth",24.0,24.0,false,"fixture",3,0)
 ui.render();await t.frames()
 var catalog=preload("res://data/encyclopedia.gd")
 t.check(ui.game.live_card_text("confluence").face_effects!=catalog.card("confluence").face_effects and ui.game.live_card_text("hannya_1").face_costs!=catalog.card("hannya_1").face_costs,"BOOK fixture has real equipment-dependent effects and mouth-dependent soup costs")
 var live_face=ui.card_buttons[held.uid]
 var live_side="free" if live_face.free_face else "bound"
 t.check(live_face.get_node("CardText/Content/CardEffect").text==ui.game.live_card_text("confluence").face_effects[live_side],"BOOK hand cards retain live equipment-dependent effects")
 var before=ui.game.export_snapshot()
 ui._open_drawer("show_encyclopedia");await t.frames()
 var book=ui.find_child("Encyclopedia",true,false)
 for type in ["confluence","self_binding","magic_hand","hannya_1"]:
  book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id==type)[0]);await t.frames()
  for member in [type]+catalog.related_cards(type):
   var card=catalog.card(member)
   var face=ui.find_child("DisplayCard_encyclopedia_"+member,true,false)
   if member=="magic_hand":
    var labels=face.get_node("CardKeywords").get_children()
    var cost=face.get_node("CardCost");var title=face.get_node("CardTitle");var mana=face.get_node("CardMana")
    t.check(labels.size()==2 and labels[1].position.x>=labels[0].get_rect().end.x+8,"BOOK first opening lays out enlarged keyword widths without overlap")
    t.check(cost.get_rect().get_center()==Vector2(28.5,28.5) and title.get_rect().get_center().y==28.5 and mana.get_rect().get_center().y==28.5,"BOOK enlarged cost circle, title and mana badge share a vertical center")
   for index in range(2):
    var side="free" if face.free_face else "bound"
    var rendered=face.get_node("CardText/Content/CardEffect").text
    var tags=face.get_node("CardKeywords").get_children().map(func(label):return label.text)
    var expected=Array(card.face_effects[side].split("。",false));expected.sort()
    var displayed=Array(rendered.split("。",false))+tags;displayed.sort()
    t.check(face.get_node("CardCost").text==card.face_costs[side] and displayed==expected,"BOOK preserves base effect sentences across body and bottom keywords on both faces: "+member+"/"+side)
    var badges=face.get_node("CardMana").get_children()
    t.check(badges.size()==card.face_mana[side].size() and card.face_mana[side].all(func(entry):return t.visible_text(face.get_node("CardMana/Mana_"+entry.kind)).strip_edges()==entry.text),"BOOK mana badges use static values or formulas: "+member+"/"+side)
    face.mouse_entered.emit();await t.frames()
    var tip=ui.find_child("TermExplanation",true,false)
    t.check(tip==null or not t.visible_text(tip).contains("施法成功率 · "),"BOOK tooltip excludes current casting chance: "+member+"/"+side)
    face.flip_requested.emit();await t.frames()
 t.check(ui.game.export_snapshot()==before,"BOOK static browsing and flipping preserve the live run")
 await t.close_information()
