extends RefCounted
const Store=preload("res://core/save_store.gd")
const Click=preload("res://tests/interface_ui_cases.gd")
const Pointer=preload("res://tests/target_sidebar_ui_cases.gd")

static func boot(t, store) -> void:
 var old=t.ui;t.root.remove_child(old);old.queue_free()
 t.ui=load("res://main.tscn").instantiate();t.ui.saves=store
 t.ui.display_settings.path="res://build/home-display-%s.cfg" % Time.get_ticks_usec()
 t.root.add_child(t.ui);await t.frames()

static func run(t) -> void:
 var store=Store.new("res://build/home-ui-"+str(Time.get_ticks_usec()))
 await boot(t,store)
 var ui=t.ui
 var initial=ui.game.export_snapshot()
 t.check(ui.show_home and ui.find_child("GameHome",true,false)!=null and ui.card_buttons.is_empty() and ui.body_buttons.is_empty(),"HOME startup contains only homepage, no gameplay controls")
 t.check(not store.has_files("tower") and ui.find_child("HomeContinue",true,false).disabled,"HOME opening app never creates a run/save and unavailable continue is disabled")
 var home_title=ui.find_child("HomeTitle",true,false)
 var disclaimer=ui.find_child("HomeDisclaimer",true,false)
 var title_area=ui.find_child("GameHome",true,false).get_children().filter(func(n):return n is Control and n.position.x<1000)
 t.check(home_title!=null and home_title.text=="紧缚尖塔" and title_area.size()==4 and title_area.has(home_title) and title_area.has(disclaimer) and title_area.has(ui.find_child("CharacterDescription",true,false)) and title_area.has(ui.find_child("HomeSettingsSaveNotice",true,false)) and ui.game.export_snapshot()==initial,"HOME left area contains title, character description, settings save notice and disclaimer without changing game state")
 t.check(disclaimer!=null and disclaimer.text.contains("免费发布") and disclaimer.text.contains("花钱购买") and disclaimer.text.contains("上当了") and disclaimer.position.x==100 and disclaimer.position.y>=800 and disclaimer.get_rect().end.y<=900 and disclaimer.get_line_count()==2 and disclaimer.get_theme_color("font_color")==Color("858585") and disclaimer.mouse_filter==Control.MOUSE_FILTER_IGNORE,"HOME disclaimer is complete, small gray text at lower left and never intercepts clicks")
 var chastity=ui.find_child("HomeChastityLocks",true,false);var down=ui.find_child("HomeChastityChanceDown",true,false);var up=ui.find_child("HomeChastityChanceUp",true,false)
 var custom=ui.find_child("HomeCursedPlateStart",true,false)
 var masochist=ui.find_child("HomeCursedPlateMasochist",true,false)
 t.check(custom!=null and masochist!=null and custom.disabled and masochist.disabled and not custom.button_pressed and not masochist.button_pressed and masochist.position.y>custom.position.y,"CUSTOM HOME cursed-plate checkboxes default off below disabled pool")
 t.check(chastity!=null and not chastity.disabled and not chastity.button_pressed and down.disabled and up.disabled and chastity.text.contains("25%"),"HOME chastity pool starts off with its 25 percent chance visible")
 await Click.press(t,"HomeChastityLocks");await Click.press(t,"HomeChastityChanceUp")
 t.check(chastity.button_pressed and not down.disabled and not up.disabled and ui.display_settings.chastity_lock_chance==30 and chastity.text.contains("30%"),"HOME pool toggle enables five-point probability arrows")
 t.check(not custom.disabled and not masochist.disabled,"CUSTOM HOME pool enables both cursed-plate checkboxes")
 await Click.press(t,"HomeCursedPlateStart")
 await Click.press(t,"HomeCursedPlateMasochist")
 t.check(custom.button_pressed and masochist.button_pressed and ui.display_settings.cursed_plate_start and ui.display_settings.cursed_plate_masochist_mode and ui.game.export_snapshot()==initial,"CUSTOM HOME checkboxes change only preferences")
 await Click.press(t,"HomeChastityLocks")
 t.check(custom.disabled and masochist.disabled and not custom.button_pressed and not masochist.button_pressed and not ui.display_settings.cursed_plate_start and not ui.display_settings.cursed_plate_masochist_mode,"CUSTOM HOME disabling pool clears both cursed-plate preferences")
 await Click.press(t,"HomeChastityLocks");await Click.press(t,"HomeCursedPlateStart")
 await Click.press(t,"HomeFixedPortrait")
 t.check(custom.disabled and masochist.disabled and not custom.button_pressed and not masochist.button_pressed and not chastity.button_pressed,"CUSTOM HOME fixed portrait disables all incompatible settings")
 await Click.press(t,"HomeFixedPortrait");await Click.press(t,"HomeChastityLocks")
 for step in range(5): await Click.press(t,"HomeChastityChanceDown")
 t.check(ui.display_settings.chastity_lock_chance==5 and down.disabled and not up.disabled and chastity.text.contains("5%"),"HOME probability lower bound is five percent with only downward adjustment disabled")
 for step in range(5): await Click.press(t,"HomeChastityChanceUp")
 await t.capture("ui-102-home.png")
 await Click.press(t,"HomeTutorial")
 t.check(ui.show_tutorial and ui.show_home,"HOME tutorial opens above homepage")
 await t.close_information()
 await Click.press(t,"HomeOptions")
 t.check(ui.find_child("FeedbackSpeed",true,false)!=null and ui.find_child("DisplayMode",true,false)!=null,"HOME settings expose real speed and window controls")
 var speed=ui.find_child("FeedbackSpeed",true,false);speed.select(2);speed.item_selected.emit(2)
 t.check(ui.feedback_duration==1.8 and ui.game.export_snapshot()==initial and not store.has_files("tower"),"HOME presentation settings never mutate run or create save")
 await t.close_information()
 await Click.press(t,"HomePractice")
 t.check(ui.show_settings and ui.find_child("StartEquipmentPractice",true,false)!=null,"HOME practice uses existing configured practice menu")
 var cancel=InputEventKey.new();cancel.keycode=KEY_ESCAPE;cancel.pressed=true;t.root.push_input(cancel,true);cancel=cancel.duplicate();cancel.pressed=false;t.root.push_input(cancel,true);await t.frames()
 t.check(ui.show_home and not ui.show_settings and ui.game.export_snapshot()==initial,"HOME Escape returns from practice without starting it")
 ui.persistence_enabled=false;ui.feedback_duration=0.04
 await Click.press(t,"HomeNewGame")
 t.check(not ui.show_home and ui.view.phase=="departure" and not ui.view.display_facts.is_empty() and ui.game.state.chastity_locks_enabled and ui.game.state.chastity_lock_chance==30,"HOME new tower opens floor zero with the selected chastity generation settings")
 await t.open_menu();await Click.press(t,"ReturnHome")
 t.check(ui.show_home and not ui.map_auto_travel,"HOME returning from new tower pauses navigation")
 await custom_opening(t)
 await first_battle_tutorial(t)
 await preload("res://tests/departure_ui_cases.gd").run(t)
 await henshin_practice(t)
 await iron_practice(t)
 await plate_lock_practice(t)
 await preload("res://tests/witch_character_ui_cases.gd").run(t)

static func iron_practice(t) -> void:
 var ui=t.ui
 ui._return_home();await t.frames()
 await Click.press(t,"HomePractice")
 var entry=ui.find_child("Practice_iron_man_solo",true,false)
 t.check(entry!=null and entry.text=="铁男练习","IRON HOME practice menu exposes the encounter")
 if entry==null: return
 var ancestor=entry.get_parent()
 while ancestor!=null and not ancestor is ScrollContainer: ancestor=ancestor.get_parent()
 if ancestor!=null: ancestor.ensure_control_visible(entry)
 await t.frames()
 await Click.press(t,"Practice_iron_man_solo")
 t.check(ui.view.practice_kind=="iron_man_solo" and ui.view.phase=="battle" and ui.view.enemies.size()==3,"IRON HOME native practice click opens the full real encounter")
 await t.close_information()
 var members=ui.view.enemies
 var iron=members.filter(func(e):return e.template=="iron_man")[0]
 var box=members.filter(func(e):return e.template=="binding_box")[0]
 var drone=members.filter(func(e):return e.template=="iron_drone")[0]
 t.check(ui.actor_targets[drone.id].get_global_rect().get_center().x<ui.actor_targets[box.id].get_global_rect().get_center().x and ui.actor_targets[box.id].get_global_rect().get_center().x<ui.actor_targets[iron.id].get_global_rect().get_center().x,"IRON HOME drone, box and boss appear from left to right with matching targets")
 t.check(ui.game.state.enemies.map(func(e):return e.type)==["iron_man","binding_box","iron_drone"],"IRON HOME visual positions preserve combat action order")
 t.check(await t.click("end"),"IRON HOME turn-end input commits the opening")
 t.check(ui.game.CaptureBind.has_bind(ui.game,"iron_man"),"IRON HOME opening applies the real capture state")
 t.check(ui.find_child("HeroGuardBindValue",true,false).text=="50/100","IRON HOME opening displays the three initial captures without immediate box upkeep")
 ui._return_home();await t.frames()

static func custom_opening(t) -> void:
 var ui=t.ui
 await Click.press(t,"HomeCursedPlateStart")
 await Click.press(t,"HomeCursedPlateMasochist")
 await t.capture("ui-home-custom-start.png")
 await Click.press(t,"HomeNewGame")
 t.check(ui.game.state.relics==["cursed_plate_lock"] and ui.game.state.cursed_plate_masochist_mode and ui.view.phase=="departure","CUSTOM HOME new game freezes the selected masochist version and replaces starter through engine")
 t.check(ui.find_child("DepartureOption_3",true,false)==null and ui.find_child("DepartureOption_2",true,false)!=null and ui.find_child("DepartureContinue",true,false)!=null,"CUSTOM HOME only fourth option hidden; other rewards and skip remain")
 var left=ui.find_child("DepartureOption_0",true,false);var right=ui.find_child("DepartureOption_2",true,false)
 t.check(is_equal_approx(left.position.x,1600-right.position.x-right.size.x) and ui.view.reward_panel.destination.contains("三选一"),"CUSTOM HOME three choices centered with correct explanation")
 await t.capture("ui-departure-custom-start.png")
 t.check(await t.click("departure",{"op":"choose"}),"CUSTOM HOME remaining reward commits")
 if ui.game.state.departure.stage=="card": t.check(await t.click("departure",{"op":"card"}),"CUSTOM HOME chosen card commits")
 t.check(ui.game.state.departure.stage=="done" and "cursed_plate_lock" in ui.game.state.relics,"CUSTOM HOME extra reward keeps custom starter")
 var before=ui.game.restart_snapshot()
 ui._return_home();await t.frames()
 await Click.press(t,"HomeCursedPlateStart")
 await Click.press(t,"HomeContinue")
 var resumed=ui.game.export_snapshot();before.version=resumed.version
 t.check(resumed==before and ui.game.state.relics==["cursed_plate_lock"],"CUSTOM HOME continuing uses original scene checkpoint and ignores changed custom preference")
 ui._return_home();await t.frames()

static func plate_lock_practice(t) -> void:
 var ui=t.ui
 ui._return_home();await t.frames()
 await Click.press(t,"HomePractice")
 var entry=ui.find_child("Practice_plate_lock",true,false)
 t.check(entry!=null and entry.text=="平板锁练习","PLATE LOCK HOME exposes the dedicated practice entry")
 var ancestor=entry.get_parent()
 while ancestor!=null and not ancestor is ScrollContainer: ancestor=ancestor.get_parent()
 if ancestor!=null: ancestor.ensure_control_visible(entry)
 await t.frames()
 await Click.press(t,"Practice_plate_lock")
 var locks=ui.game.state.special_equipment.filter(ui.game.SpecialEquipment.is_chastity)
 var straps=ui.game.state.special_equipment.filter(ui.game.SpecialEquipment.is_reinforcement)
 t.check(ui.view.practice_kind=="plate_lock" and ui.view.phase=="rest" and locks.size()==1 and locks[0].locked and straps.size()==1,"PLATE LOCK HOME opens the real locked root and reinforcement practice")
 t.check(ui.view.pressure.maximum==130 and ui.view.hand.any(func(card):return card.type=="unlock") and ui.body_buttons.special_2.text.contains("2"),"PLATE LOCK HOME projects the raised maximum, unlock card and two physical equipment entries")
 await t.inspect_body("special_2")
 var details=ui.find_child("EquipmentDetails",true,false)
 var lock_card=details.find_child("EquipmentCard_"+locks[0].id,true,false)
 await Pointer.press(t,lock_card.find_child("EquipmentCardDetailsToggle",true,false))
 await Pointer.press(t,lock_card.find_child("EquipmentDescriptionToggle",true,false))
 t.check(t.visible_text(lock_card).contains("状态：已上锁") and t.visible_text(details).contains("高级平板锁加固带"),"PLATE LOCK HOME visibly identifies the locked state and linked plate-lock reinforcement")
 await t.capture("ui-119-plate-lock-practice.png")
 ui._return_home()

static func henshin_practice(t) -> void:
 var ui=t.ui
 ui._return_home();await t.frames()
 await Click.press(t,"HomePractice")
 var entry=ui.find_child("Practice_henshin",true,false)
 t.check(entry!=null and entry.text=="音乐战斗练习 · henshin／般若汤-其二","MUSIC HOME practice entry names both playable song cards")
 await Click.press(t,"Practice_henshin")
 t.check(ui.view.practice_kind=="henshin" and ui.view.phase=="battle" and ui.view.enemies.size()==2,"HENSHIN HOME practice menu opens actual configured battle")
 var card=ui.view.hand.filter(func(c):return c.type=="henshin")[0]
 t.check(ui.card_buttons.has(card.uid) and ui.view.hand.any(func(c):return c.type=="hannya_henshin"),"HENSHIN HOME both versions available immediately")
 t.check(ui.view.hand.any(func(c):return c.type=="hannya_2"),"MUSIC HOME second soup is in the named practice opening hand")
 ui.card_music.configure(true,0.0)
 if ui.card_faces.get(card.uid,false): await t.flip(card.uid)
 await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid)
 t.check(ui.game.state.equipment.is_empty() and ui.card_music.playing,"HENSHIN HOME native card play releases practice equipment and starts song")
 ui._return_home();ui.card_music.configure(ui.display_settings.card_music_enabled,ui.display_settings.card_music_volume)

static func first_battle_tutorial(t) -> void:
 var ui=t.ui
 var Settings=preload("res://ui/display_settings.gd")
 var path="res://build/onboarding-%s.cfg" % Time.get_ticks_usec()
 var settings=Settings.new();settings.path=path;settings.initialize(t.root)
 ui.display_settings=settings
 t.check(not settings.fixed_hero_portrait and not settings.first_battle_tutorial_seen,"ONBOARDING fresh player defaults to normal portraits and pending tutorial")
 ui.render();await t.frames()
 t.check(ui.show_home and not ui.show_tutorial and not FileAccess.file_exists(path),"ONBOARDING homepage neither opens nor consumes first battle tutorial")
 ui.game_factory=preload("res://core/game.gd");ui.restart(42);await t.frames()
 t.check(ui.view.phase=="departure" and not ui.show_tutorial and not settings.first_battle_tutorial_seen,"ONBOARDING opening choice leaves tutorial pending")
 ui.game_factory=preload("res://tests/game_fixture.gd");ui.restart(42);await t.frames()
 var before=ui.game.export_snapshot()
 var book=ui.find_child("TutorialBook",true,false)
 t.check(ui.view.phase=="battle" and ui.show_tutorial and book!=null and book.category=="basics" and settings.first_battle_tutorial_seen,"ONBOARDING first battle opens basic controls and records the player preference")
 await t.close_information();ui.render();await t.frames()
 t.check(not ui.show_tutorial and ui.game.export_snapshot()==before,"ONBOARDING closing and rerendering never reopens or changes game state")
 var reloaded=Settings.new();reloaded.path=path;reloaded.initialize(t.root)
 t.check(reloaded.first_battle_tutorial_seen and not reloaded.fixed_hero_portrait,"ONBOARDING fresh settings instance preserves completion and default portrait")
 reloaded.set_fixed_hero_portrait(true)
 var saved=ConfigFile.new();saved.load(path)
 t.check(saved.get_value("onboarding","first_battle_tutorial_seen",false),"ONBOARDING other preference saves retain completion")
 ui.display_settings=reloaded;ui._return_home();ui.restart(43);await t.frames()
 t.check(not ui.show_tutorial,"ONBOARDING later runs and battles remain closed after reload")
 ui._open_tutorial();await t.frames()
 t.check(ui.show_tutorial,"ONBOARDING returning player can still open tutorial manually")
 await t.close_information()
 reloaded.set_fixed_hero_portrait(false)
 var fresh=Settings.new();fresh.path=path+"-other";fresh.initialize(t.root)
 t.check(not fresh.first_battle_tutorial_seen and not fresh.fixed_hero_portrait,"ONBOARDING another local profile has independent defaults")
 ui.display_settings.persistence_enabled=false
 DirAccess.remove_absolute(path)
