extends RefCounted
const Navigation=preload("res://tests/interface_ui_cases.gd")
const Queries=preload("res://ui/target_queries.gd")

static func run(t) -> void:
 await read_only_details(t)
 var ui=t.ui
 ui.restart(42)
 var fixture=preload("res://tests/link_cases.gd").precise_tool_fixture(ui.game)
 ui.render();await t.frames()
 await Navigation.press(t,"OpenItems")
 await Navigation.press(t,"ToolItem_"+fixture.tool)
 var frozen=ui.game.export_snapshot()
 await Navigation.press(t,"ToolSlot_thigh")
 t.check(ui.find_child("ToolTarget_"+fixture.link,true,false)!=null and ui.game.export_snapshot()==frozen,"CONTACT UI precise exposed connection is selectable without mutating state")
 var link_action=Queries.find(ui.view,"item",{"kind":"item_use","item":fixture.tool,"target":fixture.link})
 var link_button=ui.candidate_buttons[link_action.key]
 var scroll=link_button.get_parent()
 while scroll!=null and not scroll is ScrollContainer: scroll=scroll.get_parent()
 if scroll!=null: scroll.ensure_control_visible(link_button)
 await t.frames()
 await preload("res://tests/target_sidebar_ui_cases.gd").press(t,link_button)
 t.check(ui.game._equipment(fixture.link).durability==3 and ui.game._item(fixture.tool).uses==2 and ui.view.energy==frozen.energy,"CONTACT UI native click cuts the projected link once")
 await t.close_information()
 ui.restart(42);ui.game.state.equipment.clear();ui.game.state.items.clear();ui.game.state.wall="normal"
 var target=ui.game.add_fixture("thigh",8);ui.game._gain_tool("shard")
 var tool=ui.game.state.items[0].id;ui.render();await t.frames()
 await Navigation.press(t,"OpenItems")
 await Navigation.press(t,"ToolItem_"+tool)
 t.check(t.visible_text(ui.layout).contains("尖锐类 · 安装后可作借力环境"),"ENV UI carried sharp tool explains class and installation requirement")
 t.check(ui.find_child("ToolTarget_"+target.id,true,false)==null and ui.find_child("ToolSlot_thigh",true,false)!=null,"TOOL UI initially shows only legal position choices")
 var before=ui.game.export_snapshot()
 await Navigation.press(t,"ToolSlot_thigh")
 t.check(ui.game.export_snapshot()==before and ui.find_child("ToolTarget_"+target.id,true,false)!=null,"TOOL UI position expansion is read-only and reveals real target")
 await t.capture("ui-118-tool-position-menu.png")
 var c=Queries.find(ui.view,"item",{"kind":"item_use","item":tool,"target":target.id})
 var point=ui.candidate_buttons[c.key].get_global_rect().get_center()
 await t.move_mouse(point);await t.mouse_button(point,MOUSE_BUTTON_LEFT,true);await t.mouse_button(point,MOUSE_BUTTON_LEFT,false)
 t.check(ui.game._equipment(target.id).durability==3 and ui.game._item(tool).uses==2 and ui.view.energy==3,"TOOL UI native submenu use costs one charge and no energy")
 await t.close_information()
 ui.restart(42);ui.game.state.equipment.clear();ui.game.state.items.clear();ui.game.state.wall="normal"
 target=ui.game.add_fixture("wrist",8,10,true);ui.game._gain_tool("shard");tool=ui.game.state.items[0].id
 ui.render();await t.frames();await Navigation.press(t,"OpenItems")
 var install_actions=Queries.select(ui.view,"item",{"kind":"item_install","item":tool})
 before=ui.game.export_snapshot()
 t.check(install_actions.size()==3 and install_actions.all(func(action):return not ui.candidate_buttons.has(action.key)),"TOOL installation choices start collapsed behind one menu")
 await Navigation.press(t,"ToolInstallMenu")
 for action in install_actions:
  var button=ui.candidate_buttons.get(action.key)
  t.check(button!=null and button.text.begins_with(action.label) and button.disabled==not action.valid,"TOOL submenu preserves each formal installation label and availability")
 t.check(ui.game.export_snapshot()==before,"TOOL expanding installation menu costs no resources or turns")
 await t.capture("ui-tool-install-menu.png")
 await Navigation.press(t,"ToolInstallMenu")
 t.check(install_actions.all(func(action):return not ui.candidate_buttons.has(action.key)) and ui.game.export_snapshot()==before,"TOOL collapsing installation menu removes choices without changing state")
 t.check(await t.click("item_install",{"item":tool,"mount":"hand_wall"}),"TOOL UI installs through formal action")
 t.check(t.visible_text(ui.layout).contains("尖锐类 · 已安装"),"ENV UI installed tool retains its class label")
 t.check(t.visible_text(ui.layout).contains("伤害时触发") and Queries.select(ui.view,"item",{"kind":"item_use","item":tool}).is_empty(),"TOOL UI installed details show passive instead of direct cutting")
 await t.capture("ui-119-installed-tool-passive.png")
 await t.close_information()
 await Navigation.press(t,"ActionRailToggle")
 var tool_status=ui.find_child("StatusIcon_usable_item_"+tool,true,false)
 t.check(tool_status!=null and tool_status.find_child("StatusItemArt",true,false)!=null and t.visible_text(tool_status).contains("3"),"TOOL UI usable installed cutter has its item artwork and charge badge in the status strip")
 before=ui.game.export_snapshot()
 await Navigation.press(t,"StatusIcon_usable_item_"+tool)
 t.check(ui.show_items and ui.selected_item==tool and t.visible_text(ui.layout).contains(ui.game.Tools.mount_label("hand_wall")),"TOOL UI status shortcut opens the corresponding item and actual installation height")
 t.check(ui.game.export_snapshot()==before,"TOOL UI opening an item from status does not act or spend a charge")
 await t.close_information()
 var installed_panel=ui.find_child("InstalledTools",true,false)
 var flask=ui.find_child("ManaFlask",true,false)
 t.check(installed_panel!=null and not installed_panel.get_global_rect().intersects(flask.get_global_rect()),"TOOL installed shortcuts no longer overlap the flask")
 for control in ui.find_children("BasicAttack_*","",true,false)+[ui.find_child("DeepBreath",true,false)]:
  if control!=null: t.check(not installed_panel.get_global_rect().intersects(control.get_global_rect()),"TOOL shortcuts have reserved space beside all basic actions")
 var deposit=Queries.find(ui.view,"flask",{"op":"deposit"})
 var flask_before=ui.game.state.flask_mana
 t.check(deposit.valid,"TOOL flask deposit remains eligible after wall installation")
 await Navigation.press(t,"FlaskDeposit")
 t.check(ui.game.state.flask_mana>flask_before,"TOOL actual mouse click can still deposit mana after installation")
 await Navigation.press(t,"InstalledTool_"+tool)
 t.check(ui.show_items and ui.selected_item==tool,"TOOL relocated shortcut still opens the installed item's actions")
 await t.close_information()
 var uid=ui.view.hand.filter(func(card):return card.type=="strain")[0].uid
 if ui.card_faces.get(uid,false): await t.flip(uid)
 c=Queries.find(ui.view,"card",{"uid":uid,"target":target.id,"free":false})
 t.check(ui.detail_of(c).contains("固定切割") and c.payload.tool_bonus.damage==5,"TOOL UI card preview identifies selected fixed bonus")
 var old=target.durability;var damage=c.payload.preview.damage
 await t.start_drag(uid,"wrist")
 await t.reveal_drop_target(c.key)
 var shown=t.visible_text(ui.term_popup)
 t.check(shown.contains(ui.game.number(damage)+"点挣扎伤害") and shown.contains("另加5点切割伤害") and not shown.contains("能量"),"TOOL UI hovered target separates actual struggle and fixed cutting damage without costs")
 await t.capture("ui-120-card-tool-bonus.png")
 await t.release_target(await t.reveal_drop_target(c.key))
 t.check(is_equal_approx(ui.game._equipment(target.id).durability,old-damage-5) and ui.game._item(tool).uses==2 and ui.view.energy==1,"TOOL UI real drag pays card and triggers fixed bonus exactly once")
 ui.restart(42);await t.frames()
 t.check(ui.active_drag.is_empty() and ui.view.display_facts.map(func(entry):return Queries.fact_key(entry))==ui.game.command_facts().map(func(entry):return Queries.fact_key(entry)),"TOOL UI restarting after a target drag rebuilds facts without reading removed equipment")

static func read_only_details(t) -> void:
 var ui=t.ui
 ui.restart(42);ui.game.state.items.clear();ui.game._gain_tool("saw")
 ui.game.state.phase="map";ui.render();await t.frames()
 var before=ui.game.export_snapshot()
 await Navigation.press(t,"OpenItems")
 var text=t.visible_text(ui.layout)
 t.check(text.contains("7点真实伤害") and text.contains("剩余2次") and ui.game.Tools.TYPES.saw.materials.all(func(material):return text.contains(ui.game.Equipment.MATERIAL_NAMES[material])),"TOOL read-only inventory shows saw damage, remaining uses and every supported material")
 await Navigation.press(t,"ItemHelpToggle")
 text=t.visible_text(ui.layout)
 t.check(text.contains("安装后：") and text.contains("伤害时触发") and text.contains("消耗1次") and not text.contains("选择使用位置"),"TOOL no-action phase retains passive trigger and costs without empty target picker")
 t.check(ui.game.export_snapshot()==before,"TOOL inspecting full effects never uses a charge or mutates gameplay")
 await t.capture("ui-tool-effect-details.png")
 var shop=preload("res://core/room_services.gd").detail(ui.game,{"kind":"tool","type":"saw"})
 t.check(shop.contains("7点真实伤害") and shop.contains("共2次使用") and shop.contains("适用材料"),"TOOL shop reuses actual tool effects instead of a count-only description")
 var item_id=ui.view.items[0].id
 t.check(await t.click("item_discard",{"item":item_id}) and ui.view.items.is_empty(),"TOOL map inventory discards through the real candidate")
 t.check(ui.game.state.phase==before.phase and ui.game.state.tick==before.tick and ui.game.state.energy==before.energy and ui.game.state.mana==before.mana,"TOOL map discard costs no resources or turns")
 await t.close_information()
