extends RefCounted
const Click=preload("res://tests/interface_ui_cases.gd")
const Settings=preload("res://ui/key_bindings.gd")
const Queries=preload("res://ui/target_queries.gd")

static func key(t, code: int, down: bool=true, shift: bool=false, echo: bool=false) -> void:
 var event=InputEventKey.new();event.keycode=code;event.pressed=down;event.shift_pressed=shift;event.echo=echo
 t.root.push_input(event,true);await t.frames()

static func tap(t, code: int, shift: bool=false) -> void:
 await key(t,code,true,shift);await key(t,code,false,shift)

static func quick_region_keys(t) -> void:
 var ui=t.ui;var input=ui.keyboard_input
 var click=preload("res://tests/target_sidebar_ui_cases.gd")
 var quick=preload("res://ui/quick_release_bar.gd")
 input.settings.defaults();input.held_keys.clear();input.clear()
 ui.restart(42);await t.frames()
 var frozen=ui.game.export_snapshot()
 await click.press(t,ui.find_child("ActionRailToggle",true,false))
 var codes=[KEY_Z,KEY_X,KEY_V,KEY_F]
 for i in range(codes.size()):
  var button=ui.find_child("QuickRelease_"+quick.ORDER[i],true,false)
  t.check(button.get_node("KeyboardHint").text==input.settings.caption(quick.SLOT_ACTIONS[i]),"QUICK KEYS local toggle shows matching slot shortcut "+quick.ORDER[i])
  await tap(t,codes[i])
  t.check(ui.quick_release_region==quick.ORDER[i] and input.selection.is_empty() and ui.game.export_snapshot()==frozen,"QUICK KEYS slot selects region without attacking or spending "+quick.ORDER[i])
  var details=ui.find_child("EquipmentDetails",true,false)
  t.check(ui.show_body and details!=null and details.get_global_rect().end.y<ui.find_child("BasicActionRail",true,false).get_global_rect().position.y,"QUICK KEYS same-slot selection opens body details above rail even for an empty part")
 await tap(t,KEY_F)
 t.check(not ui.show_body and ui.quick_release_region=="region_lower" and ui.game.export_snapshot()==frozen,"QUICK KEYS same slot toggles details closed and preserves selection")
 await tap(t,KEY_F)
 t.check(ui.show_body and ui.game.export_snapshot()==frozen,"QUICK KEYS same slot reopens details without acting")
 await tap(t,KEY_I);await tap(t,KEY_Z)
 t.check(ui.show_items and ui.quick_release_region=="region_lower" and ui.game.export_snapshot()==frozen,"QUICK KEYS drawer blocks background region shortcuts")
 await tap(t,KEY_I)
 t.check(input.settings.assign("strike",0,KEY_Q),"QUICK KEYS custom slot binding accepted")
 input.refresh_hints();await t.frames()
 t.check(ui.find_child("QuickRelease_region_head",true,false).get_node("KeyboardHint").text=="Q","QUICK KEYS hint follows custom action binding")
 await tap(t,KEY_Z)
 t.check(ui.quick_release_region=="region_lower","QUICK KEYS replaced default key no longer selects region")
 await tap(t,KEY_Q)
 t.check(ui.quick_release_region=="region_head" and ui.game.export_snapshot()==frozen,"QUICK KEYS custom binding selects same slot without a second key registry")
 await click.press(t,ui.find_child("ActionRailToggle",true,false))
 await tap(t,KEY_Q)
 t.check(input.selection.get("type","")=="strike" and ui.game.export_snapshot()==frozen,"QUICK KEYS switching back restores original custom-bound attack selection")
 await tap(t,KEY_ESCAPE)
 input.settings.defaults();input.held_keys.clear();input.clear()
 ui.restart(42);await t.frames()

static func run(t) -> void:
 await quick_region_keys(t)
 await reward_navigation(t)
 var ui=t.ui;var input=ui.keyboard_input
 input.settings.defaults();input.held_keys.clear();input.clear()
 ui.restart(42);await t.frames()
 var before=ui.game.export_snapshot();var uid=ui.view.hand[0].uid
 await tap(t,KEY_1)
 t.check(ui.selected_card==uid and ui.game.state==before,"KEYS number selects a card without paying or playing")
 var old_face=ui.card_faces.get(uid,false)
 await tap(t,KEY_R)
 t.check(ui.card_faces[uid]!=old_face and ui.game.state==before,"KEYS R uses existing card flip without state changes")
 await tap(t,KEY_ESCAPE)
 t.check(ui.selected_card=="" and input.selection.is_empty() and not ui.show_menu,"KEYS Escape cancels selection before opening a menu")
 for data in [[KEY_A,"draw"],[KEY_D,"discard"],[KEY_C,"deck"],[KEY_P,"powers"]]:
  await tap(t,data[0]);t.check(ui.show_deck and ui.deck_zone==data[1],"KEYS opens correct collection "+data[1])
  await tap(t,data[0]);t.check(not ui.show_deck,"KEYS same collection key closes it")
 await tap(t,KEY_ESCAPE);t.check(ui.show_menu,"KEYS Escape opens menu when no selection")
 await tap(t,KEY_1);await tap(t,KEY_F);await tap(t,KEY_E)
 t.check(ui.game.state==before and input.selection.is_empty(),"KEYS menu blocks background card, attack and end-turn keys")
 await tap(t,KEY_ESCAPE)
 await tap(t,KEY_B);t.check(ui.show_body,"KEYS B opens body details")
 await tap(t,KEY_B);t.check(not ui.show_body,"KEYS B closes body details")
 var log_open=ui.show_log
 await tap(t,KEY_L);t.check(ui.show_log!=log_open,"KEYS L toggles action log")
 await tap(t,KEY_L);t.check(ui.show_log==log_open,"KEYS L restores prior action log visibility")
 await tap(t,KEY_F)
 t.check(input.selection.get("type","")=="fireball" and not input.choices.is_empty() and ui.game.state==before,"KEYS fireball selects formal targets without firing")
 var c=input.choices[input.choice_index]
 await key(t,KEY_SPACE)
 var after=ui.game.export_snapshot()
 t.check(after.energy==before.energy-c.cost and after.mana<before.mana,"KEYS confirm submits one real fireball and pays actual costs")
 await key(t,KEY_SPACE,true,false,true);await key(t,KEY_SPACE,false)
 t.check(ui.game.state==after,"KEYS held confirmation never repeats an action")
 ui.restart(42);await t.frames()
 await tap(t,KEY_Z);await tap(t,KEY_R)
 t.check(ui.attack_forms.get("strike",0)==1 and ui.view.energy==3,"KEYS basic attack switches via the original right-click route")
 await tap(t,KEY_ESCAPE)
 ui.game._discard_end()
 var card=preload("res://tests/curse_cases.gd").give(ui.game,"mana_invocation")
 ui.render();await t.frames();before=ui.game.export_snapshot()
 await tap(t,KEY_1)
 t.check(ui.game.state==before and not input.choices.is_empty(),"KEYS self-target card is selected without immediate use")
 await tap(t,KEY_ENTER)
 t.check(ui.view.energy==before.energy-1 and not ui.view.hand.any(func(item):return item.uid==card.uid),"KEYS Enter uses a self-target card through the original action")
 ui.restart(42);await t.frames();await tap(t,KEY_F)
 var stale=input.selection.version
 ui.game.state.version+=1;ui.render();await t.frames();before=ui.game.export_snapshot()
 await tap(t,KEY_ENTER)
 t.check(ui.view.version>stale and ui.game.state==before and input.selection.is_empty(),"KEYS a changed snapshot invalidates pending keyboard targets")
 ui.restart(42);await t.frames();ui.game._discard_end()
 var first=ui.game.add_fixture("wrist",300,1000);var second=ui.game.add_fixture("ankle",300,1000)
 card=preload("res://tests/curse_cases.gd").give(ui.game,"strain")
 ui.render();await t.frames();before=ui.game.export_snapshot()
 await tap(t,KEY_1)
 t.check(input.choices.size()>=2 and ui.body_buttons.values().any(func(button):return button.get_meta("target_selectable",false)),"KEYS restraint card reuses the shared legal targets and body highlighting")
 var queries=preload("res://ui/target_queries.gd")
 var initial=queries.fact_key(input.choices[input.choice_index])
 await tap(t,KEY_TAB)
 t.check(queries.fact_key(input.choices[input.choice_index])!=initial and ui.game.state==before,"KEYS Tab cycles a target without submitting")
 await tap(t,KEY_TAB,true)
 t.check(queries.fact_key(input.choices[input.choice_index])==initial,"KEYS Shift Tab returns to the previous target")
 c=input.choices[input.choice_index]
 var ankle=ui.body_buttons.ankle.get_global_rect().get_center()
 await t.move_mouse(ankle);await t.mouse_button(ankle,MOUSE_BUTTON_LEFT,true);await t.mouse_button(ankle,MOUSE_BUTTON_LEFT,false)
 await tap(t,KEY_SPACE)
 t.check(ui.view.energy==before.energy-c.cost and ui.game._equipment(first.id).durability==300 and ui.game._equipment(second.id).durability<300,"KEYS mouse-selected body target takes precedence when confirming the card")
 ui.restart(42);await t.frames();before=ui.game.export_snapshot()
 await tap(t,KEY_F)
 var attack=input.choices[0]
 var enemy=attack.payload.enemy
 var button=ui.actor_targets[enemy];var point=button.get_global_rect().get_center()
 await t.move_mouse(point);await t.mouse_button(point,MOUSE_BUTTON_LEFT,true);await t.mouse_button(point,MOUSE_BUTTON_LEFT,false)
 t.check(ui.view.energy==before.energy-attack.cost and ui.view.mana==before.mana-attack.mana_payment.mana and input.selection.is_empty(),"KEYS mouse can finish a keyboard-selected attack through the original target and pay its current first-shot cost")
 ui.restart(42);await t.frames();input.settings.hold_end=true
 before=ui.game.export_snapshot()
 await key(t,KEY_E);await key(t,KEY_E,false)
 t.check(ui.game.state==before,"KEYS short press cannot end turn in hold mode")
 await key(t,KEY_E)
 input._notification(Node.NOTIFICATION_APPLICATION_FOCUS_OUT)
 await t.create_timer(0.55).timeout;await t.frames();await key(t,KEY_E,false)
 t.check(ui.game.state==before,"KEYS focus loss cancels pending end-turn hold")
 await key(t,KEY_E)
 t.check(not input.end_hold.is_empty(),"KEYS held end-turn arms the current candidate")
 await t.create_timer(0.6).timeout;await t.frames();await key(t,KEY_E,false)
 t.check(ui.view.round>before.round,"KEYS completed hold submits the real end-turn candidate")
 input.settings.hold_end=false
 ui.restart(42);await t.frames();before=ui.game.export_snapshot();await tap(t,KEY_E)
 t.check(ui.view.round>before.round,"KEYS default end key submits on a single press")
 await t.open_menu();await Click.press(t,"OpenOptions");await Click.press(t,"SettingsTab_keys")
 t.check(ui.find_child("KeyBinding_card_1_0",true,false)!=null and ui.find_child("HoldEndTurn",true,false)!=null,"KEYS settings has an independent keys tab and hold preference")
 ui.find_child("HoldEndTurn",true,false).grab_focus();await tap(t,KEY_SPACE)
 t.check(input.settings.hold_end,"KEYS focused settings checkbox uses native keyboard activation")
 await tap(t,KEY_SPACE)
 before=ui.game.export_snapshot()
 await Click.press(t,"KeyBinding_card_1_0");await tap(t,KEY_E)
 t.check(input.settings.bindings.card_1[0]==KEY_1 and input.capture_id=="card_1" and input.binding_message.contains("结束回合"),"KEYS conflicting binding is rejected with the conflicting action name")
 await tap(t,KEY_G)
 t.check(input.settings.bindings.card_1[0]==KEY_G and input.capture_id=="" and ui.game.state==before,"KEYS rebinding changes preferences only")
 t.check(ui.card_buttons[ui.view.hand[0].uid].get_node("KeyboardHint").text=="G","KEYS visible hints follow the rebound key")
 await Click.press(t,"KeyBinding_card_1_0");await tap(t,KEY_ESCAPE)
 t.check(ui.show_options and input.capture_id=="" and input.settings.bindings.card_1[0]==KEY_G,"KEYS Escape cancels capture without closing settings or changing binding")
 var path="res://build/keyboard-settings-%d.cfg" % OS.get_process_id()
 var saved=Settings.new();saved.path=path;saved.bindings=input.settings.bindings.duplicate(true);saved.hold_end=true;saved.save()
 var loaded=Settings.new();loaded.path=path;loaded.initialize(true)
 t.check(loaded.bindings.card_1[0]==KEY_G and loaded.hold_end,"KEYS independent settings persist across a fresh instance")
 DirAccess.remove_absolute(path)
 await t.capture("ui-key-bindings.png")
 await tap(t,KEY_ESCAPE);await tap(t,KEY_1)
 t.check(input.selection.is_empty(),"KEYS previous key no longer selects a card after rebinding")
 await tap(t,KEY_G)
 t.check(ui.selected_card==ui.view.hand[0].uid and ui.game.state==before,"KEYS rebound key selects the real hand card")
 await tap(t,KEY_ESCAPE);await t.open_menu();await Click.press(t,"OpenOptions")
 # Reset control is below the scroll list but outside its clipping region.
 await Click.press(t,"ResetKeyBindings")
 t.check(input.settings.bindings.card_1[0]==KEY_1 and not input.settings.hold_end and ui.game.state==before,"KEYS restore defaults preserves the game")
 await tap(t,KEY_ESCAPE);await tap(t,KEY_C)
 var search=ui.find_child("DeckSearch",true,false);search.grab_focus();before=ui.game.export_snapshot()
 await tap(t,KEY_E);await tap(t,KEY_F);await tap(t,KEY_1)
 t.check(ui.show_deck and ui.game.state==before and input.selection.is_empty(),"KEYS focused text entry never invokes game shortcuts")
 await tap(t,KEY_ESCAPE)
 ui.restart(42,true,"shop");await t.frames()
 var offer=Queries.select(ui.view,"service",{"op":"take","payment":"self"}).filter(func(item):return item.valid)[0]
 ui.command_router.emit(String(offer.payload.get("kind","")),offer);await t.frames();before=ui.game.export_snapshot()
 t.check(ui.find_child("ShopPaymentPerformance",true,false)!=null,"KEYS shop purchase opens a real payment modal")
 await tap(t,KEY_M);await tap(t,KEY_I);await tap(t,KEY_ESCAPE)
 t.check(not ui.show_route and not ui.show_items and not ui.show_menu and ui.game.state==before,"KEYS payment modal blocks background navigation and Escape")
 await tap(t,KEY_TAB);await tap(t,KEY_ENTER)
 t.check(ui.find_child("ShopPaymentPerformance",true,false)==null and ui.game.state==before,"KEYS payment modal confirms its own button without a second purchase")
 ui.shop_performance_seen="";ui.render(ui.view);await t.frames()
 t.check(ui.modal_region()!=null,"KEYS mobile back fixture uses the same visible modal boundary")
 ui._notification(Node.NOTIFICATION_WM_GO_BACK_REQUEST);await t.frames()
 t.check(ui.modal_region()==null and not ui.show_menu and ui.game.state==before,"KEYS mobile back closes the payment modal via its original button without opening a background menu or paying again")
 ui.options_tab="display";input.settings.defaults();input.held_keys.clear();input.clear()

static func reward_navigation(t) -> void:
 var ui=t.ui;var input=ui.keyboard_input
 input.settings.defaults();input.held_keys.clear();input.clear()
 ui.restart(42);ui.game._finish_battle();ui.render();await t.frames()
 var before=ui.game.export_snapshot()
 await tap(t,KEY_TAB)
 var root_panel=ui.find_child("BattleRewards",true,false)
 var root_focus=t.root.gui_get_focus_owner()
 t.check(root_focus!=null and root_panel.is_ancestor_of(root_focus) and ui.game.state==before,"KEYS reward list navigation stays inside the visible reward panel without claiming")
 await Click.press(t,"Reward_card")
 await tap(t,KEY_TAB)
 var panel=ui.find_child("BattleRewards",true,false)
 var focus=t.root.gui_get_focus_owner()
 t.check(focus!=null and panel.is_ancestor_of(focus),"KEYS unified reward choices keep Tab focus inside their own panel")
 var type=ui.game.state.reward_options[0]
 var card=ui.find_child("RewardChoice_"+type,true,false)
 await t.move_mouse(card.get_global_rect().get_center())
 var face=ui.card_faces.get("reward_"+type,false)
 await tap(t,KEY_R)
 t.check(ui.card_faces.get("reward_"+type,false)!=face and ui.game.state==before,"KEYS R flips a hovered reward card without claiming it")
 card.grab_focus();await tap(t,KEY_ENTER)
 t.check(ui.game.state.reward_claimed.get("card","")==type and ui.game.state.deck.size()==before.deck.size()+1,"KEYS Enter claims a focused unified reward exactly once")
 before=ui.game.export_snapshot();await tap(t,KEY_ENTER)
 t.check(ui.game.state==before,"KEYS reward redraw does not leave confirmation focused on an already claimed card")
 ui.restart(42);preload("res://tests/boss_relic_cases.gd").boss_reward(ui.game);ui.render();await t.frames()
 await Click.press(t,"Reward_relic")
 panel=ui.find_child("BattleRewards",true,false);await tap(t,KEY_TAB)
 focus=t.root.gui_get_focus_owner()
 t.check(focus!=null and panel.is_ancestor_of(focus),"KEYS Boss relic choices share the reward keyboard focus boundary")
 var relic=ui.view.battle_rewards.filter(func(row):return row.has("choices"))[0].choices[0].id
 ui.find_child("BossRelicChoice_"+relic,true,false).grab_focus();await tap(t,KEY_ENTER)
 t.check(ui.game.state.reward_claimed.get("relic","")==relic and relic in ui.view.relics.map(func(row):return row.id),"KEYS Boss relic confirmation grants the focused original reward")
 ui.restart(42);await t.frames()
