extends RefCounted
const Click=preload("res://tests/interface_ui_cases.gd")
const Art=preload("res://ui/pixel_art.gd")
const Portrait=preload("res://ui/equipment_portrait.gd")
const Queries=preload("res://ui/target_queries.gd")

static func run(t) -> void:
 var ui=t.ui
 var factory=ui.game_factory
 ui.game_factory=preload("res://core/game.gd")
 ui._return_home();await t.frames()
 var select=ui.find_child("CharacterSelect",true,false)
 t.check(select.item_count==2 and select.get_item_text(0)=="魔法少女(futa)" and select.get_item_text(1)=="小魔女·测试版","WITCH UI character selection displays both requested names in their original order")
 var before=ui.game.export_snapshot()
 select.select(1);select.item_selected.emit(1);await t.frames()
 t.check(ui.selected_character=="witch" and ui.game.state==before and t.visible_text(ui.find_child("CharacterDescription",true,false)).contains("11张"),"WITCH UI selection changes next-run choice only")
 await t.capture("ui-witch-selection.png")
 await Click.press(t,"HomeNewGame")
 t.check(ui.game.Character.active(ui.game) and ui.game.state.deck.size()==11 and ui.view.phase=="departure","WITCH UI new game starts selected character through normal opening")
 t.check(await t.click("departure",{"op":"skip"}),"WITCH UI completes opening through candidate")
 ui.game_factory=preload("res://tests/game_fixture.gd");ui.restart(42);await t.frames()
 var hero=ui.find_child("HeroArt",true,false)
 var sidebar=ui.find_child("EquipmentPortrait",true,false)
 t.check(not hero.fixed_portrait and hero.get_node("HeroPose").texture==Art.WITCH_POSES.stand and sidebar.texture==Portrait.WITCH_SIDEBAR and not ui.view.body_groups.any(func(body):return body.id=="special_2"),"WITCH UI uses its standing and sidebar art and removes the incompatible body region")
 var button=ui.find_child("BasicAttack_witch_hand",true,false)
 t.check(button!=null and Queries.select(ui.view,"attack").all(func(c):return c.payload.get("witch_action",false)),"WITCH UI replaces original attacks with four paired basic actions")
 t.check(await t.click("attack",{"type":"witch_hand","form":0}),"WITCH UI charge submits the real action")
 t.check(ui.game.state.witch_charges.hand==1 and ui.view.statuses.any(func(row):return row.id=="witch_charge_hand" and row.value=="1层"),"WITCH UI charge count updates in status")
 t.check(await t.click("attack",{"type":"witch_hand","form":0}) and ui.game.state.witch_charges.hand==2,"WITCH UI builds multiple layers through real actions")
 button=ui.find_child("BasicAttack_witch_hand",true,false)
 var point=button.get_global_rect().get_center()
 await t.mouse_button(point,MOUSE_BUTTON_RIGHT,true)
 await t.mouse_button(point,MOUSE_BUTTON_RIGHT,false)
 t.check(ui.attack_forms.witch_hand==1 and t.visible_text(ui.find_child("BasicAttack_witch_hand",true,false)).contains("烈焰箭"),"WITCH UI right-click selects charged release without charge mutation")
 await t.capture("ui-witch-battle.png")
 t.check(await t.click("attack",{"type":"witch_hand","form":1}) and ui.game.state.witch_charges.hand==0,"WITCH UI release consumes all accumulated hand layers")
 t.check(ui.attack_forms.witch_hand==0 and t.visible_text(ui.find_child("BasicAttack_witch_hand",true,false)).contains("手部施法"),"WITCH UI release resets the selected body action to preparation")
 await preload("res://tests/witch_revision_ui_cases.gd").run(t)
 ui.game_factory=factory
 ui._return_home();await t.frames()
 select=ui.find_child("CharacterSelect",true,false);select.select(0);select.item_selected.emit(0)
 await Click.press(t,"HomeNewGame")
 t.check(not ui.game.Character.active(ui.game) and ui.game.state.deck.size()==10,"WITCH UI switches back to untouched original starter")
